<?php

    require_once "controladores/plantilla.controlador.php";//se realiza el llamado al archivo....

    $plantilla = new PlantillaControlador();//se realiza el controlador de la clase...
    
    $plantilla->plantilla();//se ejecuta metodo...

?>